### PR TITLE
Fix null time when GPS not available in GW

### LINKED ISSUE #187: Basic-Station: get null time in uplink message
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-gateway-bridge) of this repository and believe that this is not a duplicate.

## What happened?
we have enabled GPS in our basic-station gateway but we are not getting time in the uplink message.

**Can we use `rxtime` for uplink time if GPS is not available?** 

## Could you share your log output?
image

## Your Environment

| Component           | Version |
| --------------------| ------- |
| Gateway Bridge      | v3.10.0  |

### PR DESCRIPTION
**Pull request by sagar-patel-sls**
Fixes #187 

@brocaar Please review this implementation.

### CODE REVIEW

File: internal/backend/basicstation/structs/radio_meta_data.go [hunk 1]
```diff
@@ -83,6 +85,15 @@ func SetRadioMetaDataToProto(loraBand band.Band, gatewayID lorawan.EUI64, rmd Ra
 			return errors.Wrap(err, "timestamp proto error")
 		}
 
+	} else {
```
Comment (brocaar) [inline internal/backend/basicstation/structs/radio_meta_data.go:88]: Given that both the `rxtime` and `gpstime` are provided, I think it is better that both are handled individually, such that:

* `GPSTime` gets mapped to `TimeSinceGpsEpoch` and
* `RxTime` gets mapped to `Time`

The above conversion (`gpsTimeTime := time.Time(gps.NewTimeFromTimeSinceGPSEpoch(gpsTimeDur))`) was there since I wasn't aware that also the `rxtime` was provided (or it was introduced in a later version) and I wanted to set the `Time` field.

Thus:

```go
if gpsTime := rmd.UpInfo.GPSTime; gpsTime != 0 {

}

if rxTime := rmd.UpInfo.RxTime; rxTime != 0 {

}
```

Comment (sagar-patel-sls) [reply internal/backend/basicstation/structs/radio_meta_data.go:88]: @brocaar 
Yes, it's better to handle individually
I'II make changes and update this PR

Thanks

**Review by brocaar — APPROVED** [review]
